### ISSUE TITLE
判断是否为字符串的问题

### ISSUE THREAD

**Issue by itcbx** [GoSSIP-SJTU/Armariris#1]
在StringObfuscation.cpp中的runOnModule里，判断是否为字符串用gv->getName().str().find(".str.")，会导致第一个@.str识别不出来，同时char p[] = "world"这种形式的字符串生成的名称是@.main.p，导致也识别不出来，我将判断的方式改为isa<ConstantDataSequential>(gv->getInitializer())可以正常识别，不过这样子也有问题，这仅限于程序中只有char*字符串才能正常运行，如果是Objective-C中的NSString字符串，使用该方法混淆后，运行会出现`bus error`错误。
不知有没有其他方法能对NSString的字符串进行加密。

**Comment by flysoar** [comment]
十分感谢,我们对OC的测试尚不充分.在编写这个Pass的时候,我只考虑到了char*的情况,对其他情况没有多做考虑.我会尽快的处理这个问题.但最近有其他工作需要处理,bug修复可能延迟,十分抱歉.

**Comment by flysoar** [comment]
问一下,你运行的平台是X86还是ARM?

**Comment by itcbx** [comment]
在mac下编译的llvm，然后测试的是x86版的ObjectiveC，参数
clang -fobjc-arc -S -emit-llvm -mllvm -sobf test.m

**Comment by itcbx** [comment]
后来我把那段copy旧的gv的attribute的那个语句注释掉，NSString就能正常混淆了，因为原本NSString引用的char*字符串，section段里有个常量标识，强行修改内容会导致错误。不过这样子就改变了NSString的不可变属性了，不知有没有安全隐患。

**Comment by flysoar** [comment]
我认为应该没多大的安全隐患,十分感谢,稍后我将会将你的修改添加到我这边.

**Comment by itcbx** [comment]
已提交pr.

**Comment by flysoar** [comment]
十分感谢,已合并
