### ISSUE TITLE
抖音似乎抄的是你们的实现，而且没有按照Apache许可证做任何公开声明

### ISSUE THREAD

**Issue by Naville** [GoSSIP-SJTU/Armariris#20]
![82F4289C-86FB-417C-BBF1-2D0718CB54E0](https://user-images.githubusercontent.com/5205699/58558749-89405a00-8219-11e9-82c8-5de8959e97a5.png)
火山小视频相关字符串，可以某种程度上证明确实来自字节跳动
![DA9EE6C5-51BE-46D1-9DF0-139C8F9C1964](https://user-images.githubusercontent.com/5205699/58558816-aaa14600-8219-11e9-81b8-e98d6942baab.png)

样本链接: https://cdn.discordapp.com/attachments/566987266313158656/583070306449489937/libcms.so

出于某种神必原因安卓版抄的是你们，iOS版抄的是我的。奇妙深刻的思维能力急需大脑升级，，，

所以问题的关键来了，他(们)是付钱给你们买下了使用授权还是单纯的剽窃

**Comment by yangwenbo** [comment]
光看binary不确定的啊 FLA本身ollvm也有

**Comment by GoSSIP-SJTU** [comment]
It's hard to distinguish from binary and disassemble result, maybe a modified version of ollvm and we have made several changes to ollvm version. Maybe we can blame them for not following the license derived from ollvm.

**Comment by Naville** [comment]
@yangwenbo 我说的是字符串加密的datadiv_decode不是FLA，这个只有OLLVM的某个PR和Armariris有

**Comment by Naville** [comment]
@GoSSIP-SJTU we are talking about the datadiv_decode variable, which only exists in one of OLLVM’s PR(A very buggy one!) and Armariris.
Considering how buggy the PR was, it’s at least very likely the one used by ByteDance is a slightly modified / direct copy-paste of Armariris

EDIT:
Yes, I'm fully aware that to precisely & accurately judge the origin would require some heavy disassemble/de-obfuscation of the aforementioned sample. But at least it's safe to say their implementation is at least related to yours to some certain degree

**Comment by Naville** [comment]
![image](https://user-images.githubusercontent.com/5205699/58713329-3eaa1380-83ba-11e9-86f0-1be930b64701.png)
嗯，连用``llvm.global_ctors`` 都完美符合Armariris的特征，实锤了

**Comment by GoSSIP-SJTU** [comment]
Actually that's a bad implementation.... I have reimplemented the feature such that the strings are re-encrypted after being used.
